trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*
  paths:
    exclude:
    - CHANGELOG.md
    - LICENSE
    - README.md

schedules:
- cron: 0 14 * * 0
  displayName: Weekly CI build
  branches:
    include:
    - master
  always: true

stages:
- stage: Test
  jobs:

  - job: Test_Linux
    pool:
      vmImage: ubuntu-18.04
    variables:
      test_realm: domain.test
    strategy:
      matrix:
        Python36:
          python.version: 3.6
        Python37:
          python.version: 3.7
        Python38:
          python.version: 3.8
        Python39:
          python.version: 3.9

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)

    - script: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          gss-ntlmssp \
          libkrb5-dev \
          python-dev
      displayName: Install system requirements

    - script: |
        echo "Installing baseline pip packages"
        python -m pip install --upgrade pip poetry

        echo "Installing requirements"
        poetry install -E kerberos -E credssp
        poetry update
      displayName: Install

    - script: |
        poetry run pycodestyle pypsrp --verbose --show-source --statistics --max-line-length 119
      displayName: Lint

    - script: |
        poetry run py.test -v --junitxml junit/test-results.xml --cov pypsrp --cov-report xml --cov-report term-missing
      displayName: Test

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: $(Agent.OS) - $(Build.BuildNumber) - Python $(python.version)
      displayName: Publish test results
      condition: succeededOrFailed()

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml

    - script: |
        bash <(curl -s https://codecov.io/bash)
      displayName: Upload to codecov.io
      continueOnError: true
      timeoutInMinutes: 5

  - job: Test_Windows
    pool:
      vmImage: windows-2019
    strategy:
      matrix:
        Python36-x86:
          python.version: 3.6
          python.arch: x86
        Python36-x64:
          python.version: 3.6
          python.arch: x64
        Python37-x86:
          python.version: 3.7
          python.arch: x86
        Python37-x64:
          python.version: 3.7
          python.arch: x64
        Python38-x86:
          python.version: 3.8
          python.arch: x86
        Python38-x64:
          python.version: 3.8
          python.arch: x64
        Python39-x86:
          python.version: 3.9
          python.arch: x86
        Python39-x64:
          python.version: 3.9
          python.arch: x64

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)
        architecture: $(python.arch)

    - script: |
        echo "Installing baseline pip packages"
        python -m pip install --upgrade pip poetry

        echo "Installing requirements"
        poetry install -E kerberos -E credssp
        poetry update
      displayName: Install

    - script: |
        poetry run python -m pycodestyle pypsrp --verbose --show-source --statistics --max-line-length 119
      displayName: Lint

    - script: |
        poetry run python -m pytest -v --junitxml junit/test-results.xml --cov pypsrp --cov-report xml --cov-report term-missing
      displayName: Test

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: $(Agent.OS) - $(Build.BuildNumber) - Python $(python.version) $(python.arch)
      displayName: Publish test results
      condition: succeededOrFailed()

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml

    - script: |
        choco.exe install codecov --yes --no-progress
        codecov.exe -f coverage.xml
      displayName: Upload to codecov.io
      continueOnError: true
      timeoutInMinutes: 5

- stage: Publish
  jobs:

  - job: Publish
    pool:
      vmImage: ubuntu-18.04

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.8

    - script: |
        echo "Installing baseline pip packages"
        python -m pip install --upgrade pip poetry twine
      displayName: Install build requirements

    - script: |
        python -m poetry build
      displayName: Build universal wheel and sdist

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: dist
        artifactName: wheels

    - task: TwineAuthenticate@1
      displayName: Twine Authenticate
      condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/v'))
      inputs:
        pythonUploadServiceConnection: pypi

    - script: |
        python -m twine upload -r pypi --config-file $(PYPIRC_PATH) dist/*
      condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/v'))
      displayName: Publish artifact to Pypi

