# Copyright: (c) 2023, Jordan Borean (@jborean93) <jborean93@gmail.com>
# MIT License (see LICENSE or https://opensource.org/licenses/MIT)

from __future__ import annotations

from ._auth import (
    AuthProvider,
    BasicAuth,
    NegotiateAuth,
    WSManCertificateAuth,
    WSManCredSSPAuth,
    WSManEncryptionProvider,
)
from ._client import (
    NAMESPACES,
    CommandEvent,
    CommandResponseEvent,
    CommandState,
    ConnectEvent,
    ConnectResponseEvent,
    CreateEvent,
    CreateResponseEvent,
    DeleteEvent,
    DeleteResponseEvent,
    DisconnectEvent,
    DisconnectResponseEvent,
    EnumerateEvent,
    EnumerateResponseEvent,
    FaultAddressingEvent,
    FaultEvent,
    GetEvent,
    GetResponseEvent,
    OptionSet,
    PullEvent,
    PullResponseEvent,
    PutEvent,
    PutResponseEvent,
    ReceiveEvent,
    ReceiveResponseEvent,
    ReconnectEvent,
    ReconnectResponseEvent,
    SelectorSet,
    SendEvent,
    SendResponseEvent,
    SignalCode,
    SignalEvent,
    SignalResponseEvent,
    WSManAction,
    WSManClient,
    WSManEvent,
)
from ._exceptions import (
    ErrorCancelled,
    OperationAborted,
    OperationTimedOut,
    ServiceStreamDisconnected,
    ShellDisconnected,
    UnexpectedSelectors,
    WSManAuthenticationError,
    WSManFault,
    WSManFaultCode,
    WSManHTTPError,
)
from ._http import AsyncWSManHTTP, SyncWSManHTTP
from ._tls import create_ssl_context
from ._winrs import CommandInfo, WinRS

__all__ = [
    "NAMESPACES",
    "AsyncWSManHTTP",
    "CommandEvent",
    "CommandInfo",
    "CommandResponseEvent",
    "CommandState",
    "ConnectEvent",
    "ConnectResponseEvent",
    "CreateEvent",
    "CreateResponseEvent",
    "DeleteEvent",
    "DeleteResponseEvent",
    "DisconnectEvent",
    "DisconnectResponseEvent",
    "EnumerateEvent",
    "EnumerateResponseEvent",
    "ErrorCancelled",
    "FaultAddressingEvent",
    "FaultEvent",
    "GetEvent",
    "GetResponseEvent",
    "OperationAborted",
    "OperationTimedOut",
    "OptionSet",
    "PullEvent",
    "PullResponseEvent",
    "PutEvent",
    "PutResponseEvent",
    "ReceiveEvent",
    "ReceiveResponseEvent",
    "ReconnectEvent",
    "ReconnectResponseEvent",
    "SelectorSet",
    "SendEvent",
    "SendResponseEvent",
    "ServiceStreamDisconnected",
    "ShellDisconnected",
    "SignalCode",
    "SignalEvent",
    "SignalResponseEvent",
    "SyncWSManHTTP",
    "UnexpectedSelectors",
    "WSManAction",
    "AuthProvider",
    "WSManAuthenticationError",
    "BasicAuth",
    "WSManCertificateAuth",
    "WSManClient",
    "WSManConnectionData",
    "WSManCredSSPAuth",
    "WSManEncryptionProvider",
    "WSManEvent",
    "WSManFault",
    "WSManFaultCode",
    "WSManHTTPError",
    "NegotiateAuth",
    "WinRS",
    "create_ssl_context",
]
